import { Translations } from './types';

// API Simulation Delays (in milliseconds)
export const API_SIMULATION_DELAY_SHORT = 500;
export const API_SIMULATION_DELAY_MEDIUM = 1500;
export const API_SIMULATION_DELAY_LONG = 3000;

// Fare Calculation
export const PER_KM_RATE = 10; // INR per kilometer
export const MINIMUM_FARE = 30; // INR minimum fare
export const COMMISSION_PER_RIDE = 1; // INR commission for the platform

// Driver Search Radius (in kilometers)
export const DRIVER_SEARCH_RADIUS_KM = 5;

// Translation Strings
export const ENGLISH_TRANSLATIONS: Translations = {
  appName: 'Local E-Rickshaw Finder',
  login: 'Login',
  phoneNumber: 'Phone Number',
  enterPhoneNumber: 'Enter Phone Number',
  sendOtp: 'Send OTP',
  otp: 'OTP',
  enterOtp: 'Enter OTP',
  verifyOtp: 'Verify OTP',
  selectRole: 'Select Role:',
  user: 'User',
  driver: 'Driver',
  admin: 'Admin',
  logout: 'Logout',
  loading: 'Loading',
  authenticationFailed: 'Authentication failed. Please try again.',
  geolocationBlocked: 'Geolocation permission denied. Please enable it in your browser settings to use the map features.',
  geolocationError: 'Error getting location: ',
  findNearbyRickshaw: 'Find Nearby E-Rickshaw/Auto',
  yourCurrentLocation: 'Your Current Location:',
  nearbyDrivers: 'Nearby Drivers',
  distance: 'Distance',
  rating: 'Rating',
  call: 'Call',
  bookRide: 'Book Ride',
  pickupLocation: 'Pickup Location',
  dropLocation: 'Drop Location',
  confirmBooking: 'Confirm Booking',
  rideConfirmed: 'Ride Confirmed!',
  fareEstimate: 'Fare Estimate',
  driverName: 'Driver Name',
  vehicleType: 'Vehicle Type',
  driverDetails: 'Driver Details',
  pickup: 'Pickup',
  drop: 'Drop',
  status: 'Status',
  online: 'Online',
  offline: 'Offline',
  toggleOnlineStatus: 'Toggle Online Status',
  incomingRideRequests: 'Incoming Ride Requests',
  accept: 'Accept',
  reject: 'Reject',
  noRequests: 'No incoming ride requests.',
  totalRides: 'Total Rides',
  totalCommission: 'Total Commission',
  activeDrivers: 'Active Drivers',
  activeUsers: 'Active Users',
  adminPanel: 'Admin Panel',
  askGemini: 'Ask Gemini',
  askAnything: 'Ask anything about travel, e-rickshaws, or local info!',
  gettingAnswer: 'Getting answer...',
  selectLanguage: 'Select Language',
  welcome: 'Welcome',
  currentRole: 'Current Role',
};

export const HINDI_TRANSLATIONS: Translations = {
  appName: 'लोकल ई-रिक्शा फाइंडर',
  login: 'लॉगिन',
  phoneNumber: 'मोबाइल नंबर',
  enterPhoneNumber: 'मोबाइल नंबर दर्ज करें',
  sendOtp: 'ओटीपी भेजें',
  otp: 'ओटीपी',
  enterOtp: 'ओटीपी दर्ज करें',
  verifyOtp: 'ओटीपी सत्यापित करें',
  selectRole: 'भूमिका चुनें:',
  user: 'उपयोगकर्ता',
  driver: 'ड्राइवर',
  admin: 'एडमिन',
  logout: 'लॉगआउट',
  loading: 'लोड हो रहा है',
  authenticationFailed: 'प्रमाणीकरण विफल। कृपया पुनः प्रयास करें।',
  geolocationBlocked: 'भू-स्थान की अनुमति अस्वीकृत। कृपया मानचित्र सुविधाओं का उपयोग करने के लिए अपने ब्राउज़र सेटिंग्स में इसे सक्षम करें।',
  geolocationError: 'स्थान प्राप्त करने में त्रुटि: ',
  findNearbyRickshaw: 'आस-पास ई-रिक्शा/ऑटो खोजें',
  yourCurrentLocation: 'आपका वर्तमान स्थान:',
  nearbyDrivers: 'आस-पास के ड्राइवर',
  distance: 'दूरी',
  rating: 'रेटिंग',
  call: 'कॉल करें',
  bookRide: 'राइड बुक करें',
  pickupLocation: 'पिकअप स्थान',
  dropLocation: 'ड्रॉप स्थान',
  confirmBooking: 'बुकिंग की पुष्टि करें',
  rideConfirmed: 'राइड की पुष्टि हो गई!',
  fareEstimate: 'किराये का अनुमान',
  driverName: 'ड्राइवर का नाम',
  vehicleType: 'वाहन का प्रकार',
  driverDetails: 'ड्राइवर विवरण',
  pickup: 'पिकअप',
  drop: 'ड्रॉप',
  status: 'स्थिति',
  online: 'ऑनलाइन',
  offline: 'ऑफ़लाइन',
  toggleOnlineStatus: 'ऑनलाइन स्थिति बदलें',
  incomingRideRequests: 'आने वाली राइड अनुरोध',
  accept: 'स्वीकार करें',
  reject: 'अस्वीकार करें',
  noRequests: 'कोई आने वाली राइड अनुरोध नहीं है।',
  totalRides: 'कुल राइड',
  totalCommission: 'कुल कमीशन',
  activeDrivers: 'सक्रिय ड्राइवर',
  activeUsers: 'सक्रिय उपयोगकर्ता',
  adminPanel: 'एडमिन पैनल',
  askGemini: 'जेमिनी से पूछें',
  askAnything: 'यात्रा, ई-रिक्शा, या स्थानीय जानकारी के बारे में कुछ भी पूछें!',
  gettingAnswer: 'उत्तर प्राप्त हो रहा है...',
  selectLanguage: 'भाषा चुनें',
  welcome: 'आपका स्वागत है',
  currentRole: 'वर्तमान भूमिका',
};
